---

- name: Install requirements
  package: 
     name: 
       - flatpak
       - git
       - nodejs
     state: latest
  become: yes

# Jetbrains toolbox 

- name: Download jetbrains toolbox
  get_url: 
     url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.14.5179.tar.gz
     dest: /tmp/jetbrains_toolbox.tar.gz
     mode: 0550

- name: Extract jetbrains toolbox
  unarchive:
    src: /tmp/jetbrains_toolbox.tar.gz
    dest: /tmp

- name: Extract jetbrains toolbox
  unarchive:
    src: /tmp/jetbrains_toolbox.tar.gz
    dest: /tmp
    
- name: Copy jetbrains toolbox extracted folder to home
  copy:
    src: /tmp/jetbrains-toolbox-1.14.5179/jetbrains-toolbox
    dest: /home/{{ansible_user}}/
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: 0554

- name: Remove extracted folder
  file:
    path: /tmp/jetbrains-toolbox-1.14.5179
    state: absent

- name: Remove archive
  file:
    path: /tmp/jetbrains_toolbox.tar.gz
    state: absent

# Install flatpaks
# TODO: Update command to use flatpak module when issues with it are fixed

# - name: Install flatpaks
#   command: "flatpak install {{ item }} -y"
#   become: yes
#   ignore_errors: yes
#   loop: "{{ flatpak_urls }}"

- name: Install flatpaks
  flatpak:
    name: '{{ item }}'
    state: present
  loop: "{{ flatpak_urls }}"
  become: yes

# Devilbox
- name: Ensure Projects folder exists
  file:
    name: /home/{{ansible_user}}/Projects
    state: directory

- name: Check if devilbox exists
  stat:
    path: "/home/{{ansible_user}}/Projects/devilbox"
  register: devilbox

- name: Clone devilbox if it does not exist
  git:
     repo: https://github.com/cytopia/devilbox.git
     dest: /home/{{ansible_user}}/Projects/devilbox
  when: devilbox.stat.exists == false

# Configure git
- name: Create or override .gitconfig file
  template:
     src: git_config.j2
     dest: /home/{{ ansible_user }}/.gitconfig