---

- name: Install requirements
  package: 
     name: 
      - gnome-tweak-tool
      - python3-psutil
     state: present
  become: yes

# Set hostname

- name: Set the hostname of the machine
  hostname:
    name: "{{ machine_hostname }}"
  when: machine_hostname != ""


# Set number of kernels to keep to 10

- name: Set number of backup kernels
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^installonly_limit='
    line: 'installonly_limit=10'
  become: yes

# Set keyboard shortcuts

- name: Set Ctrl+Q shortcut to close a window
  dconf: 
     key: /org/gnome/desktop/wm/keybindings/close
     value: "['<Primary>q']"
     
- name: Set Super+E shortcut to open the file manager
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/home
     value: "'<Super>e'"

- name: Set Super+B shortcut to open the browser
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/www
     value: "'<Super>b'"

- name: Set Super+D shortcut to show the desktop
  dconf: 
     key: /org/gnome/desktop/wm/keybindings/show-desktop
     value: "['<Super>d']"

- name: Create binding for terminal
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/terminal_keybinding/binding
     value: "'<Primary><Alt>t'"

- name: Set the command for the terminal binding
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/terminal_keybinding/command
     value: "'gnome-terminal'"

- name: Set the name for the terminal binding
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/terminal_keybinding/name
     value: "'Terminal'"

- name: Create binding for System Monitor
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/system_monitor_keybinding/binding
     value: "'<Primary><Shift>Escape'"

- name: Set the command for the System Monitor binding
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/system_monitor_keybinding/command
     value: "'gnome-system-monitor'"

- name: Set the name for the System Monitor binding
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/system_monitor_keybinding/name
     value: "'System Monitor'"



# Note: This will override other custom keybindings
- name: Add custom keybindings
  dconf: 
     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
     value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/terminal_keybinding/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/system_monitor_keybinding/']"

# Other Gnome tweaks

- name: Set Source Code Pro Bold 11 as monospace font
  dconf: 
     key: /org/gnome/desktop/interface/monospace-font-name
     value: "'Source Code Pro Bold 11'"

- name: Set antialiasing to subpixel
  dconf: 
     key: /org/gnome/settings-daemon/plugins/xsettings/antialiasing
     value: "'rgba'"

- name: Set enabled extensions
  dconf: 
     key: /org/gnome/shell/enabled-extensions
     value: "['dash-to-dock@micxgx.gmail.com']"
  
# Set shortcut for opening terminal from nautilus
# https://stackoverflow.com/questions/48840027/ubuntu-open-terminal-in-current-folder-with-shortcut

- name: Ensure nautilus scripts folder exists
  file:
    path: /home/{{ansible_user}}/.local/share/nautilus/scripts
    state: directory

- name: Create Terminal script
  template:
    src: nautilus_terminal_script.j2
    dest: /home/{{ansible_user}}/.local/share/nautilus/scripts/Terminal

- name: Make Terminal script executable
  file:
    path: /home/{{ansible_user}}/.local/share/nautilus/scripts/Terminal
    mode: a+x

- name: Create nautilus script-accels file
  template:
    src: script-accels.j2
    dest: /home/{{ansible_user}}/.config/nautilus/scripts-accels

# Enable automatic login
- name: Set AutomaticLoginEnable to True
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: True
    mode: 0644
  become: yes
  
- name: Enable AutomaticLogin to the current user
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: "{{ansible_user}}"
    mode: 0644
  become: yes

- name: Copy background image
  copy:
     src: "{{ role_path }}/files/background.jpg"
     dest: /home/{{ansible_user}}/Pictures/background.jpg

- name: Set background image
  dconf: 
     key: /org/gnome/desktop/background/picture-uri
     value: "'file:///home/{{ansible_user}}/Pictures/background.jpg'"

- name: Copy lockscreen image
  copy:
     src: "{{ role_path }}/files/lock_screen.jpg"
     dest: /home/{{ansible_user}}/Pictures/lock_screen.jpg

- name: Set lock screen image
  dconf: 
     key: /org/gnome/desktop/screensaver/picture-uri
     value: "'file:///home/{{ansible_user}}/Pictures/lock_screen.jpg'"
 