---

- name: Import rpm key
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  become: yes

- name: Add repository
  yum_repository:
    name: brave-browser
    description: Brave Browser repo
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
  become: yes

- name: Update package manager
  dnf:
     update_cache: yes
  become: yes

- name: Install browser
  package:
    name: 
      - brave-keyring
      - brave-browser
    state: latest
  become: yes 